// web/components/ui/Toast.tsx
'use client'

import { useState, useEffect } from 'react'
import { ToastProps } from '@/types/components'

export default function Toast({ message, type, duration = 5000, onClose }: ToastProps) {
  const [isVisible, setIsVisible] = useState(true)
  const [isAnimating, setIsAnimating] = useState(false)

  useEffect(() => {
    // Pequeno delay para garantir que a animação de entrada funcione
    const enterTimer = setTimeout(() => {
      setIsAnimating(true)
    }, 10)

    const timer = setTimeout(() => {
      setIsAnimating(false)
      setTimeout(() => {
        setIsVisible(false)
        setTimeout(() => onClose?.(), 300)
      }, 300)
    }, duration)

    return () => {
      clearTimeout(timer)
      clearTimeout(enterTimer)
    }
  }, [duration, onClose])

  const getToastStyles = () => {
    switch (type) {
      case 'success':
        return 'bg-green-500 text-white border-green-600'
      case 'error':
        return 'bg-red-500 text-white border-red-600'
      case 'info':
        return 'bg-blue-500 text-white border-blue-600'
      default:
        return 'bg-gray-500 text-white border-gray-600'
    }
  }

  const getIcon = () => {
    switch (type) {
      case 'success':
        return (
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
          </svg>
        )
      case 'error':
        return (
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        )
      case 'info':
        return (
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        )
    }
  }

  if (!isVisible) return null

  return (
    <div className={`absolute top-4 right-4 z-50 transform transition-all duration-300 ease-in-out ${
      isAnimating 
        ? 'translate-x-0 opacity-100' 
        : 'translate-x-full opacity-0'
    }`}>
      <div className={`flex items-center space-x-3 px-6 py-4 rounded-lg shadow-lg border-l-4 min-w-80 max-w-96 ${getToastStyles()}`}>
        <div className="flex-shrink-0">
          {getIcon()}
        </div>
        <div className="flex-1">
          <p className="text-sm font-medium">{message}</p>
        </div>
        <button
          onClick={() => {
            setIsAnimating(false)
            setTimeout(() => {
              setIsVisible(false)
              setTimeout(() => onClose?.(), 300)
            }, 300)
          }}
          className="flex-shrink-0 ml-4 text-white hover:text-gray-200 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  )
}

// Hook para usar toast facilmente
export const useToast = () => {
  const [toasts, setToasts] = useState<Array<{ id: string; message: string; type: 'success' | 'error' | 'info' }>>([])

  const showToast = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
    const id = Math.random().toString(36).substr(2, 9)
    setToasts(prev => [...prev, { id, message, type }])
  }

  const removeToast = (id: string) => {
    setToasts(prev => prev.filter(toast => toast.id !== id))
  }

  const ToastContainer = () => (
    <div className="fixed top-4 right-4 z-50 space-y-3">
      {toasts.map((toast, index) => (
        <div 
          key={toast.id}
          className="transform transition-all duration-300 ease-in-out"
          style={{ 
            transform: `translateY(${index * 8}px)`,
            zIndex: 50 - index
          }}
        >
          <Toast
            message={toast.message}
            type={toast.type}
            onClose={() => removeToast(toast.id)}
          />
        </div>
      ))}
    </div>
  )

  return { showToast, ToastContainer }
}

// web_angular/src/app/shared/components/toast/toast.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Toast, ToastType } from '../../types/toast.types';

@Component({
  selector: 'app-toast',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './toast.component.html'
})
export class ToastComponent implements OnInit, OnDestroy {
  @Input() toast!: Toast;
  @Output() close = new EventEmitter<string>();

  isVisible = true;
  isAnimating = false;
  private timeoutId?: number;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    setTimeout(() => {
      this.isAnimating = true;
      this.cdr.markForCheck();
    }, 10);

    if (this.toast.duration && this.toast.duration > 0) {
      this.timeoutId = window.setTimeout(() => this.dismiss(), this.toast.duration);
    }
  }

  ngOnDestroy(): void {
    if (this.timeoutId) {
      clearTimeout(this.timeoutId);
    }
  }

  dismiss(): void {
    this.isAnimating = false;
    setTimeout(() => {
      this.isVisible = false;
      setTimeout(() => {
        this.close.emit(this.toast.id);
      }, 300);
    }, 300);
  }

  getToastStyles(): string {
    const baseStyles = 'border-l-4 shadow-lg';
    switch (this.toast.type) {
      case 'success':
        return `${baseStyles} bg-green-50 border-green-500 text-green-900`;
      case 'error':
        return `${baseStyles} bg-red-50 border-red-500 text-red-900`;
      case 'warning':
        return `${baseStyles} bg-yellow-50 border-yellow-500 text-yellow-900`;
      case 'info':
        return `${baseStyles} bg-blue-50 border-blue-500 text-blue-900`;
      default:
        return `${baseStyles} bg-slate-50 border-slate-500 text-slate-900`;
    }
  }

  getIcon(): string {
    switch (this.toast.type) {
      case 'success':
        return `<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
        </svg>`;
      case 'error':
        return `<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>`;
      case 'warning':
        return `<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>`;
      case 'info':
        return `<svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>`;
      default:
        return '';
    }
  }
}


@if (isVisible) {
  <div 
    class="flex items-start space-x-3 px-4 py-3 rounded-lg min-w-[320px] max-w-md transition-all duration-300 ease-in-out"
    [class]="getToastStyles()"
    [class.opacity-0]="!isAnimating"
    [class.translate-x-full]="!isAnimating && (toast.position?.includes('right') || !toast.position)"
    [class.-translate-x-full]="!isAnimating && toast.position?.includes('left')"
    [class.translate-y-full]="!isAnimating && toast.position?.includes('bottom')"
    [class.-translate-y-full]="!isAnimating && toast.position?.includes('top')"
    [class.opacity-100]="isAnimating"
    [class.translate-x-0]="isAnimating && (toast.position?.includes('right') || !toast.position)"
    [class.translate-y-0]="isAnimating && toast.position?.includes('top')"
  >
    <!-- Ícone -->
    <div class="flex-shrink-0 mt-0.5" [innerHTML]="getIcon()"></div>
    
    <!-- Mensagem -->
    <div class="flex-1 min-w-0">
      <p class="text-sm font-medium leading-5 whitespace-pre-line">{{ toast.message }}</p>
    </div>
    
    <!-- Botão Fechar -->
    <button
      (click)="dismiss()"
      type="button"
      class="flex-shrink-0 ml-2 text-current hover:opacity-70 transition-opacity duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-current rounded"
      aria-label="Fechar notificação"
    >
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>
}
