// web_angular/src/app/shared/components/header/header.component.ts
import { Component, Output, EventEmitter, inject, signal, ElementRef, ViewChild, AfterViewInit, OnDestroy, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, ActivatedRoute } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

interface NavItem {
  name: string;
  href: string;
  children?: { name: string; href: string }[];
  adminOnly?: boolean;
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html'
})
export class HeaderComponent implements AfterViewInit, OnDestroy {
  private authService = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  @Output() menuClick = new EventEmitter<void>();
  @ViewChild('dropdownRef') dropdownRef!: ElementRef;
  @ViewChild('navDropdownRef') navDropdownRef!: ElementRef;

  user = this.authService.user;
  dropdownOpen = signal<boolean>(false);
  mobileMenuOpen = signal<boolean>(false);
  openDropdown = signal<string | null>(null);
  
  private clickListener?: (event: MouseEvent) => void;

  navItems: NavItem[] = [
    {
      name: 'Dashboard',
      href: '/dashboard'
    },
    {
      name: 'Operações',
      href: '/dashboard',
      children: [
        { name: 'Cadastrar Venda', href: '/dashboard?tab=cadastrar' },
        { name: 'Histórico', href: '/dashboard?tab=historico' },
        { name: 'Estoque', href: '/dashboard?tab=estoque' }
      ]
    },
    {
      name: 'Admin',
      href: '/admin',
      adminOnly: true,
      children: [
        { name: 'Histórico de Vendas', href: '/admin?tab=historico' },
        { name: 'Cadastrar Produto', href: '/admin?tab=cadastrar-produto' },
        { name: 'Listar Produtos', href: '/admin?tab=listar-produtos' },
        { name: 'Estoque de Usuários', href: '/admin?tab=estoque-usuarios' }
      ]
    }
  ];

  get filteredNavItems(): NavItem[] {
    return this.navItems.filter(item => !item.adminOnly || this.user()?.isAdmin);
  }

  ngAfterViewInit(): void {
    this.clickListener = (event: MouseEvent) => {
      if (this.dropdownRef && !this.dropdownRef.nativeElement.contains(event.target)) {
        this.closeDropdown();
      }
      if (this.navDropdownRef && !this.navDropdownRef.nativeElement.contains(event.target)) {
        this.openDropdown.set(null);
      }
    };
    document.addEventListener('click', this.clickListener);
  }

  ngOnDestroy(): void {
    if (this.clickListener) {
      document.removeEventListener('click', this.clickListener);
    }
  }

  toggleDropdown(): void {
    this.dropdownOpen.set(!this.dropdownOpen());
  }

  closeDropdown(): void {
    this.dropdownOpen.set(false);
  }

  toggleNavDropdown(itemName: string): void {
    if (this.openDropdown() === itemName) {
      this.openDropdown.set(null);
    } else {
      this.openDropdown.set(itemName);
    }
  }

  handleLogout(): void {
    this.authService.logout();
    this.router.navigate(['/']);
    this.closeDropdown();
  }

  navigate(href: string): void {
    if (href.includes('?')) {
      const [path, query] = href.split('?');
      const params = new URLSearchParams(query);
      this.router.navigate([path], { queryParams: Object.fromEntries(params) });
    } else {
      this.router.navigate([href]);
    }
    this.mobileMenuOpen.set(false);
    this.openDropdown.set(null);
  }

  isActive(href: string): boolean {
    const currentUrl = this.router.url;
    if (href === '/dashboard') {
      return currentUrl === '/dashboard' || currentUrl.startsWith('/dashboard?tab=');
    }
    if (href === '/admin') {
      return currentUrl === '/admin' || currentUrl.startsWith('/admin?tab=');
    }
    if (href.includes('?tab=')) {
      const tab = href.split('tab=')[1];
      if (href.startsWith('/admin')) {
        return currentUrl.includes(`/admin?tab=${tab}`);
      }
      return currentUrl.includes(`/dashboard?tab=${tab}`);
    }
    return currentUrl.startsWith(href);
  }

  get userInitial(): string {
    return this.user()?.nome?.charAt(0).toUpperCase() || 'U';
  }
}

<header class="sticky top-0 z-40 bg-white border-b border-slate-200 shadow-sm">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <!-- Logo e Menu Mobile -->
      <div class="flex items-center space-x-4 flex-shrink-0">
        <button
          (click)="menuClick.emit()"
          class="lg:hidden p-2 rounded-lg hover:bg-slate-100 text-slate-600 transition-colors"
          aria-label="Toggle menu"
        >
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
        
        <!-- Logo -->
        <div class="flex items-center space-x-3">
          <div class="w-10 h-10 bg-gradient-to-br from-slate-600 to-slate-800 rounded-lg flex items-center justify-center flex-shrink-0">
            <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <h1 class="hidden sm:block text-lg font-semibold text-slate-900 whitespace-nowrap">CMD Import</h1>
        </div>
      </div>

      <!-- Navegação Desktop - Centralizada -->
      <nav class="hidden lg:flex items-center space-x-1 flex-1 justify-center mx-8" #navDropdownRef>
        @for (item of filteredNavItems; track item.name) {
          @if (item.children && item.children.length > 0) {
            <div class="relative">
              <button
                (click)="toggleNavDropdown(item.name)"
                [class.text-slate-900]="isActive(item.href) || openDropdown() === item.name"
                [class.text-slate-600]="!isActive(item.href) && openDropdown() !== item.name"
                [class.font-medium]="isActive(item.href) || openDropdown() === item.name"
                class="flex items-center space-x-1 px-4 py-2 rounded-lg hover:bg-slate-50 transition-colors text-sm whitespace-nowrap"
              >
                <span>{{ item.name }}</span>
                <svg
                  [class.rotate-180]="openDropdown() === item.name"
                  class="w-4 h-4 transition-transform"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
              </button>

              <!-- Dropdown -->
              @if (openDropdown() === item.name) {
                <div class="absolute top-full left-0 mt-1 w-48 bg-white rounded-lg shadow-lg border border-slate-200 py-1 z-50">
                  @for (child of item.children; track child.href) {
                    <button
                      (click)="navigate(child.href)"
                      [class.bg-slate-50]="isActive(child.href)"
                      [class.text-slate-900]="isActive(child.href)"
                      [class.text-slate-600]="!isActive(child.href)"
                      class="w-full text-left px-4 py-2 text-sm hover:bg-slate-50 transition-colors"
                    >
                      {{ child.name }}
                    </button>
                  }
                </div>
              }
            </div>
          } @else {
            <button
              (click)="navigate(item.href)"
              [class.text-slate-900]="isActive(item.href)"
              [class.font-medium]="isActive(item.href)"
              [class.text-slate-600]="!isActive(item.href)"
              class="px-4 py-2 rounded-lg hover:bg-slate-50 transition-colors text-sm whitespace-nowrap"
            >
              {{ item.name }}
            </button>
          }
        }
      </nav>

      <!-- User Info -->
      <div class="flex items-center space-x-3 flex-shrink-0">
        <!-- User Info com Dropdown -->
        <div class="relative" #dropdownRef>
          <button
            (click)="toggleDropdown()"
            class="flex items-center space-x-2 hover:bg-slate-50 rounded-lg px-3 py-1.5 transition-colors"
          >
            <div class="hidden md:block text-right min-w-0">
              <p class="text-sm font-medium text-slate-900 truncate max-w-[120px]">{{ user()?.nome || 'Usuário' }}</p>
              <p class="text-xs text-slate-500 truncate max-w-[120px]">{{ user()?.email || '' }}</p>
            </div>
            <div class="w-9 h-9 bg-gradient-to-br from-slate-400 to-slate-600 rounded-full flex items-center justify-center shadow-sm flex-shrink-0">
              <span class="text-white text-sm font-semibold">{{ userInitial }}</span>
            </div>
            <svg
              [class.rotate-180]="dropdownOpen()"
              class="w-4 h-4 text-slate-500 transition-transform flex-shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          </button>

          <!-- Dropdown Menu -->
          @if (dropdownOpen()) {
            <div class="absolute right-0 mt-2 w-56 bg-white rounded-lg shadow-xl border border-slate-200 py-1 z-50">
              <div class="px-4 py-3 border-b border-slate-200">
                <p class="text-sm font-semibold text-slate-900">{{ user()?.nome || 'Usuário' }}</p>
                <p class="text-xs text-slate-500 truncate">{{ user()?.email || '' }}</p>
              </div>
              <button
                (click)="handleLogout()"
                class="w-full flex items-center space-x-3 px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 transition-colors"
              >
                <svg class="w-5 h-5 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                </svg>
                <span>Sair</span>
              </button>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</header>

// web/components/layout/Header.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import { useAuth } from '@/contexts/AuthContext'
import { useRouter, usePathname } from 'next/navigation'

interface HeaderProps {
  onMenuClick: () => void
}

export default function Header({ onMenuClick }: HeaderProps) {
  const { user, logout } = useAuth()
  const router = useRouter()
  const pathname = usePathname()
  const [dropdownOpen, setDropdownOpen] = useState(false)
  const dropdownRef = useRef<HTMLDivElement>(null)
  
  const isAdminPage = pathname?.startsWith('/admin') || false

  // Fechar dropdown ao clicar fora
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setDropdownOpen(false)
      }
    }

    if (dropdownOpen) {
      document.addEventListener('mousedown', handleClickOutside)
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [dropdownOpen])

  const handleLogout = () => {
    logout()
    router.push('/')
    setDropdownOpen(false)
  }

  return (
    <header className="sticky top-0 z-30 h-16 bg-white border-b border-gray-200 flex items-center justify-between px-4 lg:px-6">
      {/* Menu Toggle e Breadcrumb */}
      <div className="flex items-center space-x-4">
        <button
          onClick={onMenuClick}
          className="lg:hidden p-2 rounded-lg hover:bg-gray-100 text-gray-600"
          aria-label="Toggle menu"
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
        <div className="hidden lg:block">
          <h2 className="text-sm font-medium text-gray-500">
            {isAdminPage ? 'Painel Administrativo' : 'Dashboard'}
          </h2>
        </div>
      </div>

      {/* User Info com Dropdown */}
      <div className="relative" ref={dropdownRef}>
        <button
          onClick={() => setDropdownOpen(!dropdownOpen)}
          className="flex items-center space-x-3 hover:bg-gray-50 rounded-lg px-2 py-1.5 transition-colors"
        >
          <div className="hidden sm:block text-right">
            <p className="text-sm font-medium text-slate-900">{user?.nome || 'Usuário'}</p>
            <p className="text-xs text-gray-500">{user?.email || ''}</p>
          </div>
          <div className="w-10 h-10 bg-gradient-to-br from-slate-400 to-slate-600 rounded-full flex items-center justify-center">
            <span className="text-white text-sm font-medium">
              {user?.nome?.charAt(0).toUpperCase() || 'U'}
            </span>
          </div>
          <svg
            className={`w-4 h-4 text-gray-500 transition-transform ${dropdownOpen ? 'rotate-180' : ''}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {/* Dropdown Menu */}
        {dropdownOpen && (
          <div className="absolute right-0 mt-2 w-56 bg-white rounded-lg shadow-lg border border-gray-200 py-1 z-50">
            <div className="px-4 py-3 border-b border-gray-200">
              <p className="text-sm font-medium text-slate-900">{user?.nome || 'Usuário'}</p>
              <p className="text-xs text-gray-500 truncate">{user?.email || ''}</p>
            </div>
            <button
              onClick={handleLogout}
              className="w-full flex items-center space-x-3 px-4 py-3 text-sm text-gray-700 hover:bg-gray-50 transition-colors"
            >
              <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
              </svg>
              <span>Sair</span>
            </button>
          </div>
        )}
      </div>
    </header>
  )
}
