// web_angular/src/app/shared/components/sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, ActivatedRoute } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

interface NavItem {
  name: string;
  href: string;
  icon: string;
  adminOnly?: boolean;
}

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './sidebar.component.html'
})
export class SidebarComponent {
  private authService = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  @Input() isOpen = signal<boolean>(false);
  @Output() toggle = new EventEmitter<void>();

  user = this.authService.user;

  navItems: NavItem[] = [
    {
      name: 'Dashboard',
      href: '/dashboard',
      icon: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6'
    },
    {
      name: 'Estoque',
      href: '/dashboard?tab=estoque',
      icon: 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4'
    },
    {
      name: 'Cadastrar Venda',
      href: '/dashboard?tab=cadastrar',
      icon: 'M12 4v16m8-8H4'
    },
    {
      name: 'Histórico',
      href: '/dashboard?tab=historico',
      icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2'
    },
    {
      name: 'Painel Admin',
      href: '/admin',
      icon: 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z',
      adminOnly: true
    }
  ];

  get filteredNavItems(): NavItem[] {
    return this.navItems.filter(item => !item.adminOnly || this.user()?.isAdmin);
  }

  navigate(href: string): void {
    if (href.includes('?')) {
      const [path, query] = href.split('?');
      const params = new URLSearchParams(query);
      this.router.navigate([path], { queryParams: Object.fromEntries(params) });
    } else {
      this.router.navigate([href]);
    }
    this.toggle.emit(); // Fecha o menu mobile após navegar
  }

  isActive(href: string): boolean {
    const currentUrl = this.router.url;
    if (href === '/dashboard') {
      return currentUrl === '/dashboard' || currentUrl.startsWith('/dashboard?tab=');
    }
    if (href === '/admin') {
      return currentUrl === '/admin' || currentUrl.startsWith('/admin?tab=');
    }
    if (href.includes('?tab=')) {
      const tab = href.split('tab=')[1];
      if (href.startsWith('/admin')) {
        return currentUrl.includes(`/admin?tab=${tab}`);
      }
      return currentUrl.includes(`/dashboard?tab=${tab}`);
    }
    return currentUrl.startsWith(href);
  }
}


<!-- Overlay para mobile -->
@if (isOpen()) {
  <div
    class="fixed inset-0 bg-black/50 z-40 lg:hidden"
    (click)="toggle.emit()"
  ></div>
}

<!-- Sidebar - Apenas Mobile -->
<aside
  [class.translate-x-0]="isOpen()"
  [class.-translate-x-full]="!isOpen()"
  class="fixed top-0 left-0 h-screen bg-white border-r border-gray-200 z-50 transition-transform duration-300 ease-in-out lg:hidden flex flex-col w-64"
>
  <!-- Logo e Toggle -->
  <div class="flex items-center justify-between h-16 px-6 border-b border-gray-200">
    <div class="flex items-center space-x-3">
      <div class="w-8 h-8 bg-gradient-to-br from-slate-600 to-slate-800 rounded-lg flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      </div>
      <h1 class="text-lg font-semibold text-slate-900">CMD Import</h1>
    </div>
    <button
      (click)="toggle.emit()"
      class="lg:hidden p-1.5 rounded-lg hover:bg-gray-100 text-gray-600"
    >
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>

  <!-- Navigation -->
  <nav class="flex-1 px-4 py-6 space-y-1 overflow-y-auto">
    @for (item of filteredNavItems; track item.href) {
      <button
        (click)="navigate(item.href)"
        [class.bg-slate-100]="isActive(item.href)"
        [class.text-slate-900]="isActive(item.href)"
        [class.font-medium]="isActive(item.href)"
        [class.text-gray-600]="!isActive(item.href)"
        [class.hover:bg-gray-50]="!isActive(item.href)"
        [class.hover:text-slate-900]="!isActive(item.href)"
        class="w-full flex items-center space-x-3 px-4 py-3 rounded-lg transition-colors duration-200"
      >
        <svg
          class="w-5 h-5"
          [class.text-slate-700]="isActive(item.href)"
          [class.text-gray-500]="!isActive(item.href)"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="item.icon" />
        </svg>
        <span class="text-sm">{{ item.name }}</span>
      </button>
    }
  </nav>
</aside>

// web/components/layout/Sidebar.tsx
'use client'

import { useRouter, usePathname, useSearchParams } from 'next/navigation'
import { useAuth } from '@/contexts/AuthContext'

interface NavItem {
  name: string
  href: string
  icon: React.ReactNode
  adminOnly?: boolean
}

interface SidebarProps {
  isOpen: boolean
  onToggle: () => void
}

export default function Sidebar({ isOpen, onToggle }: SidebarProps) {
  const { user } = useAuth()
  const router = useRouter()
  const pathname = usePathname()
  const searchParams = useSearchParams()

  const navItems: NavItem[] = [
    {
      name: 'Dashboard',
      href: '/dashboard',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
        </svg>
      ),
    },
    {
      name: 'Estoque',
      href: '/dashboard?tab=estoque',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
        </svg>
      ),
    },
    {
      name: 'Cadastrar Venda',
      href: '/dashboard?tab=cadastrar',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
        </svg>
      ),
    },
    {
      name: 'Histórico',
      href: '/dashboard/historico',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
        </svg>
      ),
    },
    {
      name: 'Painel Admin',
      href: '/admin',
      icon: (
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
        </svg>
      ),
      adminOnly: true,
    },
  ]

  const filteredNavItems = navItems.filter(item => !item.adminOnly || user?.isAdmin)

  const isActive = (href: string) => {
    if (href === '/dashboard') {
      // Dashboard principal sem tab
      return pathname === '/dashboard' && !searchParams.get('tab')
    }
    if (href.includes('/dashboard?tab=')) {
      // Verificar se a tab na URL corresponde
      const tab = href.split('tab=')[1]
      return pathname === '/dashboard' && searchParams.get('tab') === tab
    }
    if (href.startsWith('/dashboard')) {
      return pathname?.startsWith(href)
    }
    return pathname?.startsWith(href)
  }

  return (
    <>
      {/* Overlay para mobile */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-40 lg:hidden"
          onClick={onToggle}
        />
      )}

      {/* Sidebar */}
      <aside
        className={`
          fixed top-0 left-0 h-screen bg-white border-r border-gray-200 z-50
          transition-transform duration-300 ease-in-out
          ${isOpen ? 'translate-x-0' : '-translate-x-full'}
          lg:translate-x-0 lg:static lg:z-auto lg:h-screen
          flex flex-col
          w-64
        `}
      >
        {/* Logo e Toggle */}
        <div className="flex items-center justify-between h-16 px-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 bg-gradient-to-br from-slate-600 to-slate-800 rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            {isOpen && (
              <h1 className="text-lg font-semibold text-slate-900">CMD Import</h1>
            )}
          </div>
          <button
            onClick={onToggle}
            className="lg:hidden p-1.5 rounded-lg hover:bg-gray-100 text-gray-600"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Navigation */}
        <nav className="flex-1 px-4 py-6 space-y-1 overflow-y-auto">
          {filteredNavItems.map((item) => {
            const active = isActive(item.href)
            return (
              <button
                key={item.href}
                onClick={() => {
                  router.push(item.href)
                  // Fechar sidebar no mobile após navegação
                  if (typeof window !== 'undefined' && window.innerWidth < 1024) {
                    onToggle()
                  }
                }}
                className={`
                  w-full flex items-center space-x-3 px-4 py-3 rounded-lg
                  transition-colors duration-200
                  ${
                    active
                      ? 'bg-slate-100 text-slate-900 font-medium'
                      : 'text-gray-600 hover:bg-gray-50 hover:text-slate-900'
                  }
                `}
              >
                <span className={active ? 'text-slate-700' : 'text-gray-500'}>
                  {item.icon}
                </span>
                <span className="text-sm">{item.name}</span>
              </button>
            )
          })}
        </nav>

      </aside>
    </>
  )
}
