// web/components/dashboard/HistoricoVendas.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { HistoricoVenda } from '@/types/venda'
import { formatDate, formatCurrency } from '@/lib/formatters'
import { HistoricoVendasProps } from '@/types/components'

export default function HistoricoVendas({ usuarioId }: HistoricoVendasProps) {
  const [vendas, setVendas] = useState<HistoricoVenda[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [paginaAtual, setPaginaAtual] = useState(1)
  const [totalPaginas, setTotalPaginas] = useState(1)
  const [totalVendas, setTotalVendas] = useState(0)
  const [filtroCliente, setFiltroCliente] = useState('')
  const [filtroDataInicio, setFiltroDataInicio] = useState('')
  const [filtroDataFim, setFiltroDataFim] = useState('')
  const [ordenacao, setOrdenacao] = useState<'mais-recente' | 'mais-antigo' | 'maior-valor' | 'menor-valor'>('mais-recente')
  const router = useRouter()
  const itensPorPagina = 10

  const carregarHistorico = useCallback(async () => {
    try {
      setLoading(true)
      const { saleApi } = await import('@/lib/api')
      const response = await saleApi.historico({
        pagina: paginaAtual,
        limite: itensPorPagina,
        ordenacao,
        usuarioId,
        cliente: filtroCliente || undefined,
        dataInicio: filtroDataInicio || undefined,
        dataFim: filtroDataFim || undefined,
      })

      if (response.success && response.data) {
        setVendas(response.data)
        setTotalPaginas(response.paginacao?.totalPaginas || 1)
        setTotalVendas(response.paginacao?.total || 0)
      } else {
        setError(response.message || 'Erro ao carregar histórico')
      }
    } catch (error) {
      setError('Erro interno do servidor')
    } finally {
      setLoading(false)
    }
  }, [paginaAtual, ordenacao, filtroCliente, filtroDataInicio, filtroDataFim, usuarioId])

  useEffect(() => {
    carregarHistorico()
  }, [carregarHistorico])

  const limparFiltros = () => {
    setFiltroCliente('')
    setFiltroDataInicio('')
    setFiltroDataFim('')
    setPaginaAtual(1)
  }

  const verDetalhesVenda = (vendaId: number) => {
    router.push(`/dashboard/venda/${vendaId}`)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Carregando histórico...</p>
        </div>
      </div>
    )
  }

  return (
    <div>
      <div className="mb-6">
        <h3 className="text-xl font-bold text-gray-900 mb-2">📊 Meu Histórico de Vendas</h3>
        <p className="text-gray-600">Acompanhe todas as suas vendas realizadas</p>
      </div>

      {/* Filtros Avançados */}
      <div className="bg-gray-50 rounded-xl p-4 mb-6">
        <h4 className="text-sm font-semibold text-gray-700 mb-4">Filtros Avançados</h4>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">
              Nome do Cliente
            </label>
            <input
              type="text"
              value={filtroCliente}
              onChange={(e) => setFiltroCliente(e.target.value)}
              placeholder="Buscar por cliente..."
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-gray-900 placeholder-gray-500"
            />
          </div>
          
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">
              Data Início
            </label>
            <input
              type="date"
              value={filtroDataInicio}
              onChange={(e) => setFiltroDataInicio(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
            />
          </div>
          
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">
              Data Fim
            </label>
            <input
              type="date"
              value={filtroDataFim}
              onChange={(e) => setFiltroDataFim(e.target.value)}
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
            />
          </div>
          
          <div>
            <label className="block text-xs font-medium text-gray-600 mb-1">
              Ordenação
            </label>
            <select
              value={ordenacao}
              onChange={(e) => setOrdenacao(e.target.value as 'mais-recente' | 'mais-antigo' | 'maior-valor' | 'menor-valor')}
              className="w-full px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-gray-900"
            >
              <option value="mais-recente">Mais Recente</option>
              <option value="mais-antigo">Mais Antigo</option>
              <option value="maior-valor">Maior Valor</option>
              <option value="menor-valor">Menor Valor</option>
            </select>
          </div>
        </div>
        
        <div className="flex justify-end mt-4">
          <button
            onClick={limparFiltros}
            className="px-4 py-2 text-sm font-medium text-gray-600 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
          >
            Limpar Filtros
          </button>
        </div>
      </div>

      {/* Lista de Vendas */}
      {error ? (
        <div className="text-center py-8">
          <div className="text-red-500 mb-2">⚠️</div>
          <p className="text-red-600">{error}</p>
        </div>
      ) : vendas.length === 0 ? (
        <div className="text-center py-12">
          <div className="text-gray-400 text-6xl mb-4">📊</div>
          <h3 className="text-lg font-medium text-gray-900 mb-2">
            {filtroCliente || filtroDataInicio || filtroDataFim ? 'Nenhuma venda encontrada' : 'Nenhuma venda realizada'}
          </h3>
          <p className="text-gray-500">
            {filtroCliente || filtroDataInicio || filtroDataFim 
              ? 'Tente ajustar os filtros de busca' 
              : 'Suas vendas aparecerão aqui quando você começar a vender'
            }
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {vendas.map((venda) => (
            <div key={venda.vendaId} className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4">
                <div>
                  <h4 className="text-lg font-semibold text-gray-900">{venda.clienteNome}</h4>
                  <p className="text-sm text-gray-600">{venda.telefone}</p>
                </div>
                <div className="mt-2 sm:mt-0 text-right">
                  <p className="text-2xl font-bold text-green-600">{formatCurrency(venda.valorTotal)}</p>
                  <p className="text-sm text-gray-500">{formatDate(venda.createdAt)}</p>
                </div>
              </div>

              {/* Lista de produtos */}
              <div className="mb-4">
                <p className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-2">
                  Produtos ({venda.produtos.length})
                </p>
                <div className="space-y-2">
                  {venda.produtos.map((produto) => (
                    <div key={produto.id} className="bg-gray-50 rounded-lg p-3 flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <div>
                          <p className="text-sm font-semibold text-gray-900">{produto.produtoNome}</p>
                          <p className="text-xs text-gray-500">Preço unitário: {formatCurrency(produto.precoUnitario)}</p>
                        </div>
                        {venda.fotoProduto && produto === venda.produtos[0] && (
                          <button
                            onClick={() => window.open(venda.fotoProduto, '_blank')}
                            className="p-1 text-blue-500 hover:text-blue-700 hover:bg-blue-50 rounded transition-colors"
                            title="Ver foto do produto"
                          >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                            </svg>
                          </button>
                        )}
                      </div>
                      <div className="flex items-center space-x-2">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                          {produto.quantidade}x
                        </span>
                        <span className="text-sm font-medium text-gray-900">
                          {formatCurrency(produto.precoUnitario)}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {venda.observacoes && (
                <div className="mb-4">
                  <p className="text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">Observações</p>
                  <p className="text-sm text-gray-700 bg-gray-50 p-3 rounded-lg">{venda.observacoes}</p>
                </div>
              )}

              <div className="flex items-center justify-between pt-4 border-t border-gray-200">
                <div className="text-xs text-gray-500">
                  Venda ID: {venda.vendaId}
                </div>
                <button
                  onClick={() => verDetalhesVenda(venda.produtos[0].id)}
                  className="px-4 py-2 bg-indigo-100 text-indigo-700 text-sm font-medium rounded-lg hover:bg-indigo-200 transition-colors"
                >
                  Ver Detalhes
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Paginação */}
      {totalPaginas > 1 && (
        <div className="mt-8 flex items-center justify-between">
          <div className="text-sm text-gray-700">
            Mostrando {((paginaAtual - 1) * itensPorPagina) + 1} a {Math.min(paginaAtual * itensPorPagina, totalVendas)} de {totalVendas} vendas
          </div>
          
          <div className="flex items-center space-x-2">
            <button
              onClick={() => setPaginaAtual(paginaAtual - 1)}
              disabled={paginaAtual === 1}
              className="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Anterior
            </button>
            
            <div className="flex space-x-1">
              {Array.from({ length: Math.min(5, totalPaginas) }, (_, i) => {
                const pagina = i + 1
                return (
                  <button
                    key={pagina}
                    onClick={() => setPaginaAtual(pagina)}
                    className={`px-3 py-2 text-sm font-medium rounded-lg ${
                      pagina === paginaAtual
                        ? 'bg-indigo-600 text-white'
                        : 'text-gray-700 bg-white border border-gray-300 hover:bg-gray-50'
                    }`}
                  >
                    {pagina}
                  </button>
                )
              })}
            </div>
            
            <button
              onClick={() => setPaginaAtual(paginaAtual + 1)}
              disabled={paginaAtual === totalPaginas}
              className="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Próxima
            </button>
          </div>
        </div>
      )}
    </div>
  )
}

// web_angular/src/app/dashboard/historico-vendas/historico-vendas.component.ts
import { Component, inject, signal, OnInit, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/services/auth.service';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { HistoricoVenda } from '../../shared/types/venda.types';
import { formatCurrency, formatDate, formatPhone } from '../../shared/utils/formatters';

@Component({
  selector: 'app-historico-vendas',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './historico-vendas.component.html'
})
export class HistoricoVendasComponent implements OnInit {
  private authService = inject(AuthService);
  private apiService = inject(ApiService);
  private toastService = inject(ToastService);
  private fb = inject(FormBuilder);

  user = this.authService.user;
  loading = signal<boolean>(true);
  vendas = signal<HistoricoVenda[]>([]);
  paginaAtual = signal<number>(1);
  totalPaginas = signal<number>(1);
  totalVendas = signal<number>(0);
  itensPorPagina = 10;
  fotoModal = signal<string | null>(null);

  filtrosForm: FormGroup;

  resumo = computed(() => {
    const vendasArray = this.vendas();
    const valorTotal = vendasArray.reduce((acc, venda) => acc + venda.valorTotal, 0);
    const ticketMedio = vendasArray.length > 0 ? valorTotal / vendasArray.length : 0;
    
    return {
      totalVendas: vendasArray.length,
      valorTotal,
      ticketMedio
    };
  });

  constructor() {
    this.filtrosForm = this.fb.group({
      cliente: [''],
      dataInicio: [''],
      dataFim: [''],
      ordenacao: ['mais-recente']
    });
  }

  ngOnInit(): void {
    this.carregarHistorico();
    
    // Recarregar quando filtros mudarem
    this.filtrosForm.valueChanges.subscribe(() => {
      this.paginaAtual.set(1);
      this.carregarHistorico();
    });
  }

  async carregarHistorico(): Promise<void> {
    const user = this.user();
    if (!user) return;

    try {
      this.loading.set(true);
      
      const formValue = this.filtrosForm.value;
      const params: any = {
        pagina: this.paginaAtual(),
        limite: this.itensPorPagina,
        ordenacao: formValue.ordenacao || 'mais-recente',
        usuarioId: user.id
      };

      if (formValue.cliente) {
        params.cliente = formValue.cliente;
      }
      if (formValue.dataInicio) {
        params.dataInicio = formValue.dataInicio;
      }
      if (formValue.dataFim) {
        params.dataFim = formValue.dataFim;
      }

      const response = await firstValueFrom(
        this.apiService.get<HistoricoVenda[]>('/vendas/historico', params)
      );

      if (response.success && response.data) {
        this.vendas.set(response.data);
        if (response.paginacao) {
          this.totalPaginas.set(response.paginacao.totalPaginas);
          this.totalVendas.set(response.paginacao.total);
        }
      } else {
        this.toastService.error(response.message || 'Erro ao carregar histórico');
      }
    } catch (error) {
      console.error('Erro ao carregar histórico:', error);
      this.toastService.error('Erro ao carregar histórico de vendas');
    } finally {
      this.loading.set(false);
    }
  }

  limparFiltros(): void {
    this.filtrosForm.reset({
      cliente: '',
      dataInicio: '',
      dataFim: '',
      ordenacao: 'mais-recente'
    });
    this.paginaAtual.set(1);
  }

  mudarPagina(pagina: number): void {
    this.paginaAtual.set(pagina);
    this.carregarHistorico();
  }

  // Usar funções do formatters compartilhado
  formatCurrency(value: number): string {
    return formatCurrency(value);
  }

  formatDate(dateString: string): string {
    if (!dateString) return '';
    const date = new Date(dateString);
    return new Intl.DateTimeFormat('pt-BR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).format(date);
  }

  formatPhone(phone: string): string {
    return formatPhone(phone);
  }

  getPaginas(): number[] {
    const total = this.totalPaginas();
    const maxPaginas = 5;
    const atual = this.paginaAtual();
    
    if (total <= maxPaginas) {
      return Array.from({ length: total }, (_, i) => i + 1);
    }
    
    const inicio = Math.max(1, atual - Math.floor(maxPaginas / 2));
    const fim = Math.min(total, inicio + maxPaginas - 1);
    
    return Array.from({ length: fim - inicio + 1 }, (_, i) => inicio + i);
  }

  min(a: number, b: number): number {
    return Math.min(a, b);
  }

  abrirFoto(fotoUrl: string, event?: Event): void {
    if (event) {
      event.stopPropagation();
    }
    this.fotoModal.set(fotoUrl);
  }

  fecharFoto(): void {
    this.fotoModal.set(null);
  }
}


<div class="space-y-8">
    <!-- Filtros -->
    <div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm mt-8">
      <h3 class="text-sm font-semibold text-slate-700 mb-4">Filtros Avançados</h3>
      <form [formGroup]="filtrosForm" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div>
          <label class="block text-xs font-medium text-slate-600 mb-2">Nome do Cliente</label>
          <input
            type="text"
            formControlName="cliente"
            placeholder="Buscar por cliente..."
            class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent text-slate-900 placeholder-slate-400"
          />
        </div>

        <div>
          <label class="block text-xs font-medium text-slate-600 mb-2">Data Início</label>
          <input
            type="date"
            formControlName="dataInicio"
            class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent text-slate-900"
          />
        </div>

        <div>
          <label class="block text-xs font-medium text-slate-600 mb-2">Data Fim</label>
          <input
            type="date"
            formControlName="dataFim"
            class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent text-slate-900"
          />
        </div>

        <div>
          <label class="block text-xs font-medium text-slate-600 mb-2">Ordenação</label>
          <select
            formControlName="ordenacao"
            class="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent text-slate-900"
          >
            <option value="mais-recente">Mais Recente</option>
            <option value="mais-antigo">Mais Antigo</option>
            <option value="maior-valor">Maior Valor</option>
            <option value="menor-valor">Menor Valor</option>
          </select>
        </div>
      </form>

      <div class="flex justify-end mt-4">
        <button
          type="button"
          (click)="limparFiltros()"
          class="px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
        >
          Limpar Filtros
        </button>
      </div>
    </div>

    <!-- Lista de Vendas -->
    @if (loading()) {
      <div class="flex items-center justify-center py-12">
        <div class="text-center">
          <div class="animate-spin rounded-full h-8 w-8 border-2 border-slate-600 border-t-transparent mx-auto mb-4"></div>
          <p class="text-slate-600">Carregando histórico...</p>
        </div>
      </div>
    } @else if (vendas().length === 0) {
      <div class="bg-white border border-slate-200 rounded-xl p-12 text-center shadow-sm">
        <div class="text-slate-400 text-6xl mb-4">📊</div>
        <h3 class="text-lg font-medium text-slate-900 mb-2">
          @if (filtrosForm.get('cliente')?.value || filtrosForm.get('dataInicio')?.value || filtrosForm.get('dataFim')?.value) {
            Nenhuma venda encontrada
          } @else {
            Nenhuma venda realizada
          }
        </h3>
        <p class="text-slate-500">
          @if (filtrosForm.get('cliente')?.value || filtrosForm.get('dataInicio')?.value || filtrosForm.get('dataFim')?.value) {
            Tente ajustar os filtros de busca
          } @else {
            Suas vendas aparecerão aqui quando você começar a vender
          }
        </p>
      </div>
    } @else {
      <!-- Cards de Vendas (Design Moderno) -->
      <div class="space-y-4">
        @for (venda of vendas(); track venda.vendaId) {
        <div 
          [class.bg-red-50]="venda.formaPagamento === 'crediario'"
          [class.border-red-200]="venda.formaPagamento === 'crediario'"
          [class.bg-white]="venda.formaPagamento !== 'crediario'"
          [class.border-slate-200]="venda.formaPagamento !== 'crediario'"
          class="rounded-xl border-2 shadow-sm hover:shadow-md transition-all duration-200 overflow-hidden">
          
          <!-- Header do Card -->
          <div class="bg-gradient-to-r from-slate-50 to-slate-100 px-6 py-4 border-b border-slate-200">
            <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <div class="flex-1">
                <div class="flex items-center gap-3 mb-2">
                  <div class="flex-1">
                    <h4 class="text-lg font-bold text-slate-900">{{ venda.clienteNome }}</h4>
                    @if (venda.endereco) {
                    <p class="text-sm text-slate-600 mt-1">{{ venda.endereco }}</p>
                    }
                  </div>
                </div>
                <div class="flex flex-wrap items-center gap-4 mt-2">
                  <div class="flex items-center gap-2 text-sm text-slate-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                    </svg>
                    <span>{{ formatPhone(venda.telefone) }}</span>
                  </div>
                  <div class="flex items-center gap-2 text-sm text-slate-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                    <span>{{ formatDate(venda.createdAt) }}</span>
                  </div>
                </div>
              </div>
              
              <div class="flex flex-col items-end gap-2">
                <span class="inline-flex items-center px-4 py-2 rounded-lg text-lg font-bold bg-green-100 text-green-800 border border-green-300">
                  {{ formatCurrency(venda.valorTotal) }}
                </span>
                @if (venda.formaPagamento === 'crediario') {
                <span class="inline-flex items-center px-2.5 py-1 rounded text-xs font-medium bg-red-100 text-red-700 border border-red-200">
                  Crédito
                </span>
                }
              </div>
            </div>
          </div>

          <!-- Produtos -->
          <div class="px-6 py-4">
            <div class="flex items-center justify-between mb-4">
              <h5 class="text-sm font-semibold text-slate-700 uppercase tracking-wide">
                Produtos ({{ venda.produtos.length }})
              </h5>
              @if (venda.fotoProduto) {
              <button (click)="abrirFoto(venda.fotoProduto!, $event)"
                class="p-1.5 text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors"
                title="Ver foto do produto">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
              </button>
              }
            </div>

            <div class="space-y-3">
              @for (produto of venda.produtos; track produto.id) {
              <div class="flex items-center justify-between p-4 bg-slate-50 rounded-lg border border-slate-200 hover:bg-slate-100 transition-colors">
                <div class="flex-1">
                  <div class="flex items-center gap-3">
                    <h6 class="font-semibold text-slate-900">{{ produto.produtoNome }}</h6>
                    <span class="inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-bold bg-blue-100 text-blue-800 border border-blue-200">
                      {{ produto.quantidade }}x
                    </span>
                  </div>
                  <p class="text-sm text-slate-600 mt-1">
                    {{ formatCurrency(produto.precoUnitario) }} cada
                    @if (produto.quantidade > 1) {
                      <span class="text-slate-500">• Subtotal: {{ formatCurrency(produto.precoUnitario * produto.quantidade) }}</span>
                    }
                  </p>
                </div>
                <div class="text-right">
                  <p class="font-bold text-slate-900">{{ formatCurrency(produto.precoUnitario * produto.quantidade) }}</p>
                </div>
              </div>
              }
            </div>

            @if (venda.observacoes) {
            <div class="mt-4 pt-4 border-t border-slate-200">
              <p class="text-xs font-medium text-slate-500 uppercase tracking-wide mb-2">Observações</p>
              <p class="text-sm text-slate-700 bg-slate-50 p-3 rounded-lg border border-slate-200">{{ venda.observacoes }}</p>
            </div>
            }
          </div>
        </div>
        }
      </div>

      <!-- Paginação -->
      @if (totalPaginas() > 1) {
        <div class="flex items-center justify-between bg-white border border-slate-200 rounded-xl p-4 shadow-sm">
          <div class="text-sm text-slate-700">
            Mostrando {{ ((paginaAtual() - 1) * itensPorPagina) + 1 }} a {{ min(paginaAtual() * itensPorPagina, totalVendas()) }} de {{ totalVendas() }} vendas
          </div>

          <div class="flex items-center space-x-2">
            <button
              (click)="mudarPagina(paginaAtual() - 1)"
              [disabled]="paginaAtual() === 1"
              class="px-3 py-2 text-sm font-medium text-slate-500 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              Anterior
            </button>

            <div class="flex space-x-1">
              @for (pagina of getPaginas(); track pagina) {
                <button
                  (click)="mudarPagina(pagina)"
                  [class.bg-slate-900]="pagina === paginaAtual()"
                  [class.text-white]="pagina === paginaAtual()"
                  [class.text-slate-700]="pagina !== paginaAtual()"
                  [class.bg-white]="pagina !== paginaAtual()"
                  [class.border]="pagina !== paginaAtual()"
                  [class.border-slate-300]="pagina !== paginaAtual()"
                  class="px-3 py-2 text-sm font-medium rounded-lg hover:bg-slate-50 transition-colors"
                >
                  {{ pagina }}
                </button>
              }
            </div>

            <button
              (click)="mudarPagina(paginaAtual() + 1)"
              [disabled]="paginaAtual() === totalPaginas()"
              class="px-3 py-2 text-sm font-medium text-slate-500 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              Próxima
            </button>
          </div>
        </div>
      }
    }
  </div>

  <!-- Modal de Foto -->
  @if (fotoModal()) {
  <div class="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4" (click)="fecharFoto()">
    <div class="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-auto" (click)="$event.stopPropagation()">
      <div class="sticky top-0 bg-white border-b border-slate-200 p-4 flex items-center justify-between z-10">
        <h3 class="text-lg font-bold text-slate-900">Foto do Produto</h3>
        <button (click)="fecharFoto()"
          class="w-8 h-8 bg-slate-100 hover:bg-slate-200 rounded-full flex items-center justify-center transition-colors">
          <svg class="w-4 h-4 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="p-6">
        <img [src]="fotoModal()!" alt="Foto do produto" class="w-full h-auto rounded-lg" />
      </div>
    </div>
  </div>
  }
