// web/app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useAuth } from '@/contexts/AuthContext'
import { useSearchParams, useRouter } from 'next/navigation'
import EstoqueSection from '@/components/dashboard/EstoqueSection'
import CadastrarVendaSection from '@/components/dashboard/CadastrarVendaSection'
import HistoricoVendas from '@/components/dashboard/HistoricoVendas'
import { saleApi } from '@/lib/api'
import { formatCurrency } from '@/lib/formatters'

interface DashboardStats {
  vendasHoje: number
  vendasTotal: number
  receitaHoje: number
  receitaTotal: number
}

export default function DashboardPage() {
  const { user } = useAuth()
  const router = useRouter()
  const searchParams = useSearchParams()
  const [loading, setLoading] = useState(true)
  const [stats, setStats] = useState<DashboardStats>({
    vendasHoje: 0,
    vendasTotal: 0,
    receitaHoje: 0,
    receitaTotal: 0,
  })
  
  const getInitialTab = (): 'dashboard' | 'estoque' | 'cadastrar' | 'historico' => {
    const tabParam = searchParams.get('tab')
    if (tabParam === 'cadastrar') return 'cadastrar'
    if (tabParam === 'historico') return 'historico'
    if (tabParam === 'estoque') return 'estoque'
    return 'dashboard'
  }
  
  const [activeTab, setActiveTab] = useState<'dashboard' | 'estoque' | 'cadastrar' | 'historico'>(getInitialTab())
  
  useEffect(() => {
    const tabParam = searchParams.get('tab')
    if (tabParam === 'cadastrar') {
      setActiveTab('cadastrar')
    } else if (tabParam === 'historico') {
      setActiveTab('historico')
    } else if (tabParam === 'estoque') {
      setActiveTab('estoque')
    } else {
      setActiveTab('dashboard')
    }
  }, [searchParams])

  // Carregar estatísticas
  useEffect(() => {
    const carregarEstatisticas = async () => {
      if (!user) return
      
      try {
        setLoading(true)
        
        // Data de hoje
        const hoje = new Date()
        hoje.setHours(0, 0, 0, 0)
        const hojeStr = hoje.toISOString().split('T')[0]
        
        // Buscar todas as vendas do usuário
        const responseTotal = await saleApi.historico({
          pagina: 1,
          limite: 1000, // Buscar muitas para calcular total
          usuarioId: user.id,
        })
        
        // Buscar vendas de hoje
        const responseHoje = await saleApi.historico({
          pagina: 1,
          limite: 1000,
          usuarioId: user.id,
          dataInicio: hojeStr,
        })
        
        if (responseTotal.success && responseTotal.data) {
          const todasVendas = responseTotal.data as any[]
          const vendasHoje = responseHoje.success && responseHoje.data ? (responseHoje.data as any[]) : []
          
          const receitaTotal = todasVendas.reduce((acc: number, venda: any) => acc + (venda.valorTotal || 0), 0)
          const receitaHoje = vendasHoje.reduce((acc: number, venda: any) => acc + (venda.valorTotal || 0), 0)
          
          setStats({
            vendasHoje: vendasHoje.length,
            vendasTotal: todasVendas.length,
            receitaHoje,
            receitaTotal,
          })
        }
      } catch (error) {
        console.error('Erro ao carregar estatísticas:', error)
      } finally {
        setLoading(false)
      }
    }
    
    if (activeTab === 'dashboard') {
      carregarEstatisticas()
    }
  }, [user, activeTab])

  if (!user) return null

  // Se tiver tab na URL, mostrar conteúdo correspondente
  if (activeTab !== 'dashboard') {
    return (
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        {activeTab === 'estoque' && <EstoqueSection usuarioId={user.id} />}
        {activeTab === 'cadastrar' && <CadastrarVendaSection usuarioId={user.id} />}
        {activeTab === 'historico' && <HistoricoVendas usuarioId={user.id} />}
      </div>
    )
  }

  return (
    <>
      {/* Welcome Section */}
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-900 mb-1">
          Bem-vindo, {user.nome}! 👋
        </h1>
        <p className="text-gray-600 text-sm">
          Acompanhe suas vendas e estatísticas
        </p>
      </div>

      {/* Stats Cards */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="bg-white rounded-lg border border-gray-200 p-6 animate-pulse">
              <div className="h-4 bg-gray-200 rounded w-24 mb-3"></div>
              <div className="h-8 bg-gray-200 rounded w-32"></div>
            </div>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
          {/* Vendas Hoje */}
          <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-600">Vendas Hoje</p>
              <div className="p-2 bg-blue-100 rounded-lg">
                <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
            </div>
            <p className="text-3xl font-bold text-slate-900">{stats.vendasHoje}</p>
            <p className="text-xs text-gray-500 mt-1">vendas realizadas hoje</p>
          </div>

          {/* Total de Vendas */}
          <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-600">Total de Vendas</p>
              <div className="p-2 bg-green-100 rounded-lg">
                <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
            <p className="text-3xl font-bold text-slate-900">{stats.vendasTotal}</p>
            <p className="text-xs text-gray-500 mt-1">vendas no total</p>
          </div>

          {/* Receita Hoje */}
          <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-600">Receita Hoje</p>
              <div className="p-2 bg-purple-100 rounded-lg">
                <svg className="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
            <p className="text-3xl font-bold text-slate-900">{formatCurrency(stats.receitaHoje)}</p>
            <p className="text-xs text-gray-500 mt-1">receita de hoje</p>
          </div>

          {/* Receita Total */}
          <div className="bg-white rounded-lg border border-gray-200 p-6 shadow-sm">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-medium text-gray-600">Receita Total</p>
              <div className="p-2 bg-orange-100 rounded-lg">
                <svg className="w-5 h-5 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                </svg>
              </div>
            </div>
            <p className="text-3xl font-bold text-slate-900">{formatCurrency(stats.receitaTotal)}</p>
            <p className="text-xs text-gray-500 mt-1">receita acumulada</p>
          </div>
        </div>
      )}

      {/* Quick Actions */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-semibold text-slate-900 mb-4">Ações Rápidas</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button
            onClick={() => router.push('/dashboard?tab=cadastrar')}
            className="flex items-center space-x-3 p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left"
          >
            <div className="p-2 bg-blue-100 rounded-lg">
              <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
              </svg>
            </div>
            <div>
              <p className="font-medium text-slate-900">Cadastrar Venda</p>
              <p className="text-sm text-gray-500">Registre uma nova venda</p>
            </div>
          </button>

          <button
            onClick={() => router.push('/dashboard?tab=estoque')}
            className="flex items-center space-x-3 p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left"
          >
            <div className="p-2 bg-green-100 rounded-lg">
              <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
            </div>
            <div>
              <p className="font-medium text-slate-900">Consultar Estoque</p>
              <p className="text-sm text-gray-500">Veja seus produtos disponíveis</p>
            </div>
          </button>

          <button
            onClick={() => router.push('/dashboard/historico')}
            className="flex items-center space-x-3 p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors text-left"
          >
            <div className="p-2 bg-purple-100 rounded-lg">
              <svg className="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
            </div>
            <div>
              <p className="font-medium text-slate-900">Ver Histórico</p>
              <p className="text-sm text-gray-500">Acompanhe todas as vendas</p>
            </div>
          </button>
        </div>
      </div>
    </>
  )
}

// web_angular/src/app/dashboard/dashboard.component.ts
import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../core/services/auth.service';
import { ApiService } from '../core/services/api.service';
import { MainLayoutComponent } from '../shared/components/main-layout/main-layout.component';
import { DashboardStats, VendaRecente, VendaPorDia, ProdutoMaisVendido } from '../shared/types/dashboard.types';
import { CadastrarVendaComponent } from './cadastrar-venda/cadastrar-venda.component';
import { HistoricoVendasComponent } from './historico-vendas/historico-vendas.component';
import { EstoqueComponent } from './estoque/estoque.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, MainLayoutComponent, CadastrarVendaComponent, HistoricoVendasComponent, EstoqueComponent],
  templateUrl: './dashboard.component.html'
})
export class DashboardComponent implements OnInit {
  private authService = inject(AuthService);
  private apiService = inject(ApiService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  user = this.authService.user;
  loading = signal<boolean>(true);
  stats = signal<DashboardStats>({
    vendasHoje: 0,
    vendasTotal: 0,
    receitaHoje: 0,
    receitaTotal: 0
  });

  vendasRecentes = signal<VendaRecente[]>([]);
  vendasPorDia = signal<VendaPorDia[]>([]);
  produtosMaisVendidos = signal<ProdutoMaisVendido[]>([]);

  activeTab = signal<'dashboard' | 'estoque' | 'cadastrar' | 'historico'>('dashboard');

  ngOnInit(): void {
    this.carregarDados();
    
    // Verificar tab da query string
    this.route.queryParams.subscribe(params => {
      const tab = params['tab'];
      if (tab === 'cadastrar') {
        this.activeTab.set('cadastrar');
      } else if (tab === 'historico') {
        this.activeTab.set('historico');
      } else if (tab === 'estoque') {
        this.activeTab.set('estoque');
      } else {
        this.activeTab.set('dashboard');
      }
    });
  }

  private async carregarDados(): Promise<void> {
    const user = this.user();
    if (!user) return;

    try {
      this.loading.set(true);

      const hoje = new Date();
      hoje.setHours(0, 0, 0, 0);
      const hojeStr = hoje.toISOString().split('T')[0];

      const ontem = new Date(hoje);
      ontem.setDate(ontem.getDate() - 1);
      const ontemStr = ontem.toISOString().split('T')[0];

      const seteDiasAtras = new Date(hoje);
      seteDiasAtras.setDate(seteDiasAtras.getDate() - 7);
      const seteDiasAtrasStr = seteDiasAtras.toISOString().split('T')[0];

      // Buscar todas as vendas
      const responseTotal = this.apiService.get<any[]>('/vendas/historico', {
        pagina: 1,
        limite: 1000,
        usuarioId: user.id
      });

      // Buscar vendas de hoje
      const responseHoje = this.apiService.get<any[]>('/vendas/historico', {
        pagina: 1,
        limite: 1000,
        usuarioId: user.id,
        dataInicio: hojeStr
      });

      // Buscar vendas de ontem
      const responseOntem = this.apiService.get<any[]>('/vendas/historico', {
        pagina: 1,
        limite: 1000,
        usuarioId: user.id,
        dataInicio: ontemStr,
        dataFim: hojeStr
      });

      // Buscar vendas dos últimos 7 dias
      const responseSeteDias = this.apiService.get<any[]>('/vendas/historico', {
        pagina: 1,
        limite: 1000,
        usuarioId: user.id,
        dataInicio: seteDiasAtrasStr
      });

      const [totalResult, hojeResult, ontemResult, seteDiasResult] = await Promise.all([
        firstValueFrom(responseTotal),
        firstValueFrom(responseHoje),
        firstValueFrom(responseOntem),
        firstValueFrom(responseSeteDias)
      ]);

      if (totalResult?.success && totalResult.data) {
        const todasVendas = totalResult.data;
        const vendasHoje = hojeResult?.success && hojeResult.data ? hojeResult.data : [];
        const vendasOntem = ontemResult?.success && ontemResult.data ? ontemResult.data : [];
        const vendasSeteDias = seteDiasResult?.success && seteDiasResult.data ? seteDiasResult.data : [];

        const receitaTotal = todasVendas.reduce((acc: number, venda: any) => acc + (venda.valorTotal || 0), 0);
        const receitaHoje = vendasHoje.reduce((acc: number, venda: any) => acc + (venda.valorTotal || 0), 0);
        const receitaOntem = vendasOntem.reduce((acc: number, venda: any) => acc + (venda.valorTotal || 0), 0);

        this.stats.set({
          vendasHoje: vendasHoje.length,
          vendasTotal: todasVendas.length,
          receitaHoje,
          receitaTotal,
          vendasOntem: vendasOntem.length,
          receitaOntem
        });

        // Vendas recentes (últimas 5)
        const recentes = vendasHoje
          .slice(0, 5)
          .map((v: any) => ({
            id: v.vendaId || v.id,
            data: v.createdAt || v.data,
            valorTotal: v.valorTotal || 0,
            clienteNome: v.clienteNome || v.cliente || 'Cliente',
            produtoNome: v.produtos?.[0]?.produtoNome || v.produtos?.[0]?.nome || 'Produto',
            produtos: v.produtos?.length || v.itens?.length || 0
          }));
        this.vendasRecentes.set(recentes);

        // Vendas por dia (últimos 7 dias) - sempre em ordem: Dom, Seg, Ter, Qua, Qui, Sex, Sáb
        const vendasPorDiaMap = new Map<string, { vendas: number; receita: number; diaSemana: string; ordem: number }>();
        const dias = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'];
        
        // Inicializar mapa com os últimos 7 dias
        for (let i = 6; i >= 0; i--) {
          const data = new Date(hoje);
          data.setDate(data.getDate() - i);
          const dataStr = data.toISOString().split('T')[0];
          const diaSemana = dias[data.getDay()];
          const ordem = data.getDay(); // 0=Dom, 1=Seg, ..., 6=Sáb
          
          vendasPorDiaMap.set(dataStr, { vendas: 0, receita: 0, diaSemana, ordem });
        }

        // Preencher com dados reais
        vendasSeteDias.forEach((venda: any) => {
          const dataVenda = (venda.data || venda.createdAt)?.split('T')[0];
          if (dataVenda && vendasPorDiaMap.has(dataVenda)) {
            const atual = vendasPorDiaMap.get(dataVenda)!;
            vendasPorDiaMap.set(dataVenda, {
              vendas: atual.vendas + 1,
              receita: atual.receita + (venda.valorTotal || 0),
              diaSemana: atual.diaSemana,
              ordem: atual.ordem
            });
          }
        });

        // Criar array ordenado do mais antigo para o mais recente (cronologicamente)
        const vendasPorDiaArray: VendaPorDia[] = [];
        for (let i = 6; i >= 0; i--) {
          const data = new Date(hoje);
          data.setDate(data.getDate() - i);
          const dataStr = data.toISOString().split('T')[0];
          const dados = vendasPorDiaMap.get(dataStr);
          
          if (dados) {
            vendasPorDiaArray.push({
              dia: dados.diaSemana,
              vendas: dados.vendas,
              receita: dados.receita
            });
          }
        }
        this.vendasPorDia.set(vendasPorDiaArray);

        // Produtos mais vendidos (simplificado - baseado nas vendas recentes)
        const produtosMap = new Map<string, { quantidade: number; receita: number; nome: string }>();
        vendasSeteDias.forEach((venda: any) => {
          const itens = venda.itens || venda.produtos || [];
          itens.forEach((item: any) => {
            const nome = item.produtoNome || item.nome || 'Produto';
            const quantidade = item.quantidade || 1;
            const preco = item.preco || item.valorUnitario || 0;
            
            if (produtosMap.has(nome)) {
              const atual = produtosMap.get(nome)!;
              produtosMap.set(nome, {
                quantidade: atual.quantidade + quantidade,
                receita: atual.receita + (preco * quantidade),
                nome
              });
            } else {
              produtosMap.set(nome, {
                quantidade,
                receita: preco * quantidade,
                nome
              });
            }
          });
        });

        const produtosArray = Array.from(produtosMap.values())
          .sort((a, b) => b.quantidade - a.quantidade)
          .slice(0, 5);
        this.produtosMaisVendidos.set(produtosArray);
      }
    } catch (error) {
      console.error('Erro ao carregar dados:', error);
    } finally {
      this.loading.set(false);
    }
  }

  setActiveTab(tab: 'dashboard' | 'estoque' | 'cadastrar' | 'historico'): void {
    this.activeTab.set(tab);
    if (tab === 'dashboard') {
      this.router.navigate(['/dashboard']);
    } else {
      this.router.navigate(['/dashboard'], { queryParams: { tab } });
    }
  }

  formatCurrency(value: number): string {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value);
  }

  formatDate(dateString: string): string {
    if (!dateString) return '';
    const date = new Date(dateString);
    return new Intl.DateTimeFormat('pt-BR', {
      day: '2-digit',
      month: '2-digit',
      hour: '2-digit',
      minute: '2-digit'
    }).format(date);
  }

  getCrescimentoVendas(): number {
    const stats = this.stats();
    if (!stats.vendasOntem || stats.vendasOntem === 0) return 0;
    return ((stats.vendasHoje - stats.vendasOntem) / stats.vendasOntem) * 100;
  }

  getCrescimentoReceita(): number {
    const stats = this.stats();
    if (!stats.receitaOntem || stats.receitaOntem === 0) return 0;
    return ((stats.receitaHoje - stats.receitaOntem) / stats.receitaOntem) * 100;
  }

  getMaxVendas(): number {
    const vendas = this.vendasPorDia();
    if (vendas.length === 0) return 1;
    return Math.max(...vendas.map(v => v.vendas), 1);
  }

  getBarHeight(vendas: number): number {
    const max = this.getMaxVendas();
    return max > 0 ? (vendas / max) * 100 : 0;
  }

  abs(value: number): number {
    return Math.abs(value);
  }
}

<app-main-layout>
  <div class="space-y-8">
    <!-- Header da Página -->
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-3xl font-bold text-slate-900">Visão Geral</h1>
        <p class="text-sm text-slate-600 mt-2">Acompanhe suas vendas e receitas</p>
      </div>
    </div>

    <!-- Cards de Estatísticas -->
    @if (loading()) {
      <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
        @for (i of [1, 2, 3, 4]; track i) {
          <div class="bg-white border border-slate-200 rounded-xl p-6 animate-pulse">
            <div class="h-4 bg-slate-200 rounded w-24 mb-3"></div>
            <div class="h-8 bg-slate-200 rounded w-32"></div>
          </div>
        }
      </div>
    } @else {
      <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
        <!-- Vendas Hoje -->
        <div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow duration-200">
          <div class="flex items-center justify-between mb-4">
            <p class="text-sm font-medium text-slate-600">Vendas Hoje</p>
            <div class="p-2.5 bg-blue-50 rounded-lg">
              <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
          </div>
          <p class="text-3xl font-bold text-slate-900 mb-1">{{ stats().vendasHoje }}</p>
          <div class="flex items-center space-x-2">
            <p class="text-xs text-slate-500">vendas realizadas hoje</p>
            @if (getCrescimentoVendas() !== 0) {
              <span [class.text-emerald-600]="getCrescimentoVendas() > 0" [class.text-red-600]="getCrescimentoVendas() < 0" class="text-xs font-medium">
                @if (getCrescimentoVendas() > 0) {
                  ↑ {{ getCrescimentoVendas().toFixed(1) }}%
                } @else {
                  ↓ {{ abs(getCrescimentoVendas()).toFixed(1) }}%
                }
              </span>
            }
          </div>
        </div>

        <!-- Vendas Total -->
        <div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow duration-200">
          <div class="flex items-center justify-between mb-4">
            <p class="text-sm font-medium text-slate-600">Total de Vendas</p>
            <div class="p-2.5 bg-emerald-50 rounded-lg">
              <svg class="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
              </svg>
            </div>
          </div>
          <p class="text-3xl font-bold text-slate-900 mb-1">{{ stats().vendasTotal }}</p>
          <p class="text-xs text-slate-500">total de vendas</p>
        </div>

        <!-- Receita Hoje -->
        <div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow duration-200">
          <div class="flex items-center justify-between mb-4">
            <p class="text-sm font-medium text-slate-600">Receita Hoje</p>
            <div class="p-2.5 bg-amber-50 rounded-lg">
              <svg class="w-5 h-5 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
          </div>
          <p class="text-3xl font-bold text-slate-900 mb-1">{{ formatCurrency(stats().receitaHoje) }}</p>
          <div class="flex items-center space-x-2">
            <p class="text-xs text-slate-500">receita de hoje</p>
            @if (getCrescimentoReceita() !== 0) {
              <span [class.text-emerald-600]="getCrescimentoReceita() > 0" [class.text-red-600]="getCrescimentoReceita() < 0" class="text-xs font-medium">
                @if (getCrescimentoReceita() > 0) {
                  ↑ {{ getCrescimentoReceita().toFixed(1) }}%
                } @else {
                  ↓ {{ abs(getCrescimentoReceita()).toFixed(1) }}%
                }
              </span>
            }
          </div>
        </div>

        <!-- Receita Total -->
        <div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow duration-200">
          <div class="flex items-center justify-between mb-4">
            <p class="text-sm font-medium text-slate-600">Receita Total</p>
            <div class="p-2.5 bg-purple-50 rounded-lg">
              <svg class="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
              </svg>
            </div>
          </div>
          <p class="text-3xl font-bold text-slate-900 mb-1">{{ formatCurrency(stats().receitaTotal) }}</p>
          <p class="text-xs text-slate-500">receita acumulada</p>
        </div>
      </div>
    }

    <!-- Conteúdo Adicional (apenas quando não está em outras tabs) -->
    @if (activeTab() === 'dashboard' && !loading()) {
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Gráfico de Vendas (Últimos 7 dias) -->
        <div class="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
          <div class="flex items-center justify-between mb-6">
            <h2 class="text-lg font-semibold text-slate-900">Vendas dos Últimos 7 Dias</h2>
          </div>
          <div class="space-y-4">
            @for (dia of vendasPorDia(); track dia.dia) {
              <div class="flex items-center space-x-4">
                <div class="w-12 text-sm font-medium text-slate-600">{{ dia.dia }}</div>
                <div class="flex-1">
                  <div class="flex items-center space-x-2">
                    <div class="flex-1 bg-slate-100 rounded-full h-8 overflow-hidden">
                      <div 
                        class="bg-gradient-to-r from-blue-500 to-blue-600 h-full rounded-full flex items-center justify-end pr-2 transition-all duration-300"
                        [style.width.%]="getBarHeight(dia.vendas)"
                      >
                        @if (dia.vendas > 0) {
                          <span class="text-xs font-medium text-white">{{ dia.vendas }}</span>
                        }
                      </div>
                    </div>
                    <div class="w-24 text-right">
                      <p class="text-sm font-semibold text-slate-900">{{ formatCurrency(dia.receita) }}</p>
                    </div>
                  </div>
                </div>
              </div>
            }
          </div>
        </div>

        <!-- Vendas Recentes -->
        <div class="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
          <div class="flex items-center justify-between mb-6">
            <h2 class="text-lg font-semibold text-slate-900">Vendas Recentes</h2>
            <button
              (click)="setActiveTab('historico')"
              class="text-sm text-slate-600 hover:text-slate-900 transition-colors"
            >
              Ver todas
            </button>
          </div>
          @if (vendasRecentes().length === 0) {
            <div class="text-center py-8">
              <p class="text-sm text-slate-500">Nenhuma venda hoje</p>
            </div>
          } @else {
            <div class="space-y-3">
              @for (venda of vendasRecentes(); track venda.id) {
                <div class="flex items-start justify-between p-4 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer">
                  <div class="flex-1 min-w-0">
                    <p class="text-sm font-semibold text-slate-900 truncate">{{ venda.clienteNome || venda.cliente || 'Cliente' }}</p>
                    <p class="text-xs text-slate-600 mt-1 truncate">{{ venda.produtoNome || 'Produto' }}</p>
                    <div class="flex items-center space-x-3 mt-2">
                      <p class="text-xs text-slate-500">{{ formatDate(venda.data) }}</p>
                      @if (venda.produtos && venda.produtos > 1) {
                        <span class="text-xs text-slate-400">•</span>
                        <p class="text-xs text-slate-400">{{ venda.produtos }} produtos</p>
                      }
                    </div>
                  </div>
                  <div class="ml-4 flex-shrink-0">
                    <p class="text-sm font-bold text-emerald-600">{{ formatCurrency(venda.valorTotal) }}</p>
                  </div>
                </div>
              }
            </div>
          }
        </div>
      </div>

      <!-- Produtos Mais Vendidos -->
      @if (produtosMaisVendidos().length > 0) {
        <div class="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
          <h2 class="text-lg font-semibold text-slate-900 mb-6">Produtos Mais Vendidos (7 dias)</h2>
          <div class="space-y-3">
            @for (produto of produtosMaisVendidos(); track produto.nome; let i = $index) {
              <div class="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
                <div class="flex items-center space-x-4 flex-1">
                  <div class="w-8 h-8 bg-slate-200 rounded-lg flex items-center justify-center">
                    <span class="text-sm font-bold text-slate-600">#{{ i + 1 }}</span>
                  </div>
                  <div class="flex-1">
                    <p class="text-sm font-medium text-slate-900">{{ produto.nome }}</p>
                    <p class="text-xs text-slate-500">{{ produto.quantidade }} unidade(s)</p>
                  </div>
                </div>
                <div class="text-right">
                  <p class="text-sm font-semibold text-slate-900">{{ formatCurrency(produto.receita) }}</p>
                </div>
              </div>
            }
          </div>
        </div>
      }
    }

    <!-- Seções de Conteúdo Baseadas na Tab -->
    @if (activeTab() === 'estoque') {
      <app-estoque />
    }

    @if (activeTab() === 'cadastrar') {
      <div class="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
        <app-cadastrar-venda />
      </div>
    }

          @if (activeTab() === 'historico') {
            <app-historico-vendas />
          }
  </div>
</app-main-layout>
